### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Nemcorp/layoutacademy#2]
I see you have no LICENSE for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later or GPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Nemcorp** [comment]
Thank you for pointing this out. I don't spend much time working with this project at the moment, but that may change in the future.

**Comment by Nemcorp** [comment]
I have just updated the license of this project to AGPL-3.0

**Comment by Nemcorp** [comment]
License updated

**Comment by TechnologyClassroom** [comment]
Did you choose AGPL-3.0-only or AGPL-3.0-or-later? The only difference is that AGPL-3.0-or-later would also be compatible with future versions when/if they become available.
